# ssl.cnf - Development use only.
# spell-checker: disable

[ req ]
distinguished_name  = req
req_extensions      = v3_req
x509_extensions     = v3_req

[ v3_req ]
basicConstraints        = CA:TRUE
keyUsage                = cRLSign, keyCertSign, digitalSignature

[ v3_web_client ]
basicConstraints = CA:FALSE
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid,issuer
keyUsage = digitalSignature, nonRepudiation
extendedKeyUsage = clientAuth
subjectAltName = @alt_web_client

[ alt_web_client ]
DNS.1 = web

[ v3_dev_server ]
basicConstraints = CA:FALSE
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid,issuer
keyUsage = digitalSignature, nonRepudiation
extendedKeyUsage = serverAuth
subjectAltName = @alt_dev_server

[ alt_dev_server ]
DNS.1 = localhost
DNS.2 = dev
IP.1 = 127.0.0.1
