services:
  web:
    image: "nginx:alpine"
    networks:
      - interconnect
    ports:
      - "8080-8089:80"
      - "8443-8452:443"
    restart: no
    volumes:
      - ./web/nginx.conf.d:/etc/nginx/conf.d:ro
      - ./web/public:/var/www/html:ro
      - ./web/ssl:/etc/ssl/local:ro
    healthcheck:
      test: [ "CMD", "curl", "-k", "-f", "https://localhost/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  interconnect:
    driver: bridge
