version: "3"
services:
  web:
    image: nginx:alpine-slim
    ports:
      - 8082:80
    environment:
      - NGINX_PORT=80
      - BACKEND_HOST=dev:5062
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d:ro
