# ssl.cnf - Development use only.
# spell-checker: disable

[ req ]
distinguished_name  = req_distinguished_name
req_extensions      = v3_req
x509_extensions     = v3_server

[ req_distinguished_name ]

[ v3_req ]
basicConstraints        = CA:FALSE
keyUsage                = digitalSignature, keyEncipherment

[ v3_server ]
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always,issuer
basicConstraints        = CA:FALSE
keyUsage                = digitalSignature, keyEncipherment
extendedKeyUsage        = serverAuth
subjectAltName          = @alt_names

[alt_names]
DNS.1 = localhost
IP.1 = 127.0.0.1
