#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
MEMORY_DIR="$ROOT_DIR/.serena/memories"
OUTPUT_FILE="$MEMORY_DIR/workspace_state.md"
SKIP_WINDOW_SECONDS="${SERENA_MEMORY_SKIP_WINDOW_SECONDS:-600}"
FORCE_REFRESH=false

if [ "${1:-}" = "--force" ]; then
    FORCE_REFRESH=true
fi

mkdir -p "$MEMORY_DIR"

if [ "$FORCE_REFRESH" = false ] && [ -f "$OUTPUT_FILE" ] && [ "$SKIP_WINDOW_SECONDS" -gt 0 ] 2>/dev/null; then
    NOW_EPOCH=$(date +%s)
    FILE_EPOCH=$(stat -c %Y "$OUTPUT_FILE")
    AGE_SECONDS=$((NOW_EPOCH - FILE_EPOCH))

    if [ "$AGE_SECONDS" -lt "$SKIP_WINDOW_SECONDS" ]; then
        printf 'Skipped %s (age=%ss, window=%ss)\n' "$OUTPUT_FILE" "$AGE_SECONDS" "$SKIP_WINDOW_SECONDS"
        exit 0
    fi
fi

git_value() {
    if "$@" 2>/dev/null; then
        return 0
    fi

    printf 'unknown'
}

CURRENT_BRANCH=$(git_value git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD)
DEFAULT_BRANCH=$(git_value git -C "$ROOT_DIR" symbolic-ref --short refs/remotes/origin/HEAD | sed 's#^origin/##')
LAST_COMMIT=$(git_value git -C "$ROOT_DIR" log -1 --pretty=format:%h\ %s)
GENERATED_AT=$(date -u +"%Y-%m-%d %H:%M:%SZ")

STATUS_SUMMARY=$(git -C "$ROOT_DIR" status --short 2>/dev/null | awk '
BEGIN {
    modified = 0
    added = 0
    deleted = 0
    renamed = 0
    copied = 0
    untracked = 0
}
{
    indexStatus = substr($0, 1, 1)
    worktreeStatus = substr($0, 2, 1)

    if (indexStatus == "?" && worktreeStatus == "?") {
        untracked++
        next
    }

    if (indexStatus == "A" || worktreeStatus == "A") added++
    if (indexStatus == "M" || worktreeStatus == "M") modified++
    if (indexStatus == "D" || worktreeStatus == "D") deleted++
    if (indexStatus == "R" || worktreeStatus == "R") renamed++
    if (indexStatus == "C" || worktreeStatus == "C") copied++
}
END {
    printf("modified=%d, added=%d, deleted=%d, renamed=%d, copied=%d, untracked=%d", modified, added, deleted, renamed, copied, untracked)
}')

PROJECT_LIST=$(find "$ROOT_DIR/src" -type f -name '*.csproj' -printf '%h\n' 2>/dev/null | sed "s#^$ROOT_DIR/src/##" | LC_ALL=C sort -u)

{
    printf '# Workspace State\n\n'
    printf '_Generated by scripts/update-serena-memory.sh on postAttach or manual execution._\n\n'
    printf '## Session Snapshot\n\n'
    printf -- '- GeneratedAtUtc: %s\n' "$GENERATED_AT"
    printf -- '- RepoRoot: %s\n' "$ROOT_DIR"
    printf -- '- CurrentBranch: %s\n' "$CURRENT_BRANCH"
    printf -- '- DefaultBranch: %s\n' "$DEFAULT_BRANCH"
    printf -- '- LastCommit: %s\n' "$LAST_COMMIT"
    printf -- '- GitStatus: %s\n' "$STATUS_SUMMARY"
    printf -- '- BuildTask: dotnet: build\n'
    printf -- '- RefreshCommand: ./scripts/update-serena-memory.sh\n\n'

    printf '## Project Paths\n\n'
    if [ -n "$PROJECT_LIST" ]; then
        printf '%s\n' "$PROJECT_LIST" | while IFS= read -r projectName; do
            printf -- '- %s\n' "$projectName"
        done
    else
        printf -- '- unknown\n'
    fi
} > "$OUTPUT_FILE"

printf 'Updated %s\n' "$OUTPUT_FILE"